### ISSUE TITLE
Welp latest commit kills hyprland

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#10]
After the latest commit (49b45918dbd1ced373e0178975392afe7b817350) , the plugin is causing Hyprland v0.30.0 to crash with the following error logs:

Error Logs:

https://paste.rs/g3B9L
https://paste.rs/qEqBt
https://paste.rs/LOwKI
[coredump](https://paste.rs/rL7Rh)

Steps to Reproduce:

To reproduce the issue, follow these steps:

- Use the latest version of Hyprland (v0.30.0).
- Enable the plugin.
- Use the toggle group dispatcher on a single client.

Expected Behavior:

The plugin should work as expected and not cause any errors or crashes in Hyprland.

Actual Behavior:

After enabling the plugin and using the toggle group dispatcher on a single client, it triggers the mentioned error logs and crashes the Compositor.

 On  Hyprland version: 0.30.0

**Comment by ItsDrike** [comment]
Interesting, I developed the plugin from latest master, specifically from Hyprland built from commit https://github.com/hyprwm/Hyprland/commit/161fee1d. I'll look into backporting to v0.30.0 in a few hours, or tomorrow.

**Comment by ItsDrike** [comment]
Oh nevermind, I missed that this was an issue about triggering autogroup for a single window, while using it with multiple works. This is indeed an issue on the latest Hyprland too. Fixed in ab36aeeae7f3516cb1834c46eb5f4c7d93ba3fe5
