### ISSUE TITLE
[Feature request] add support for hyprpm

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#11]
In the git branch [hyprpm](https://wiki.hyprland.org/Plugins/Using-Plugins/) is a new method of installing plugins in hyprland
Currently installing this plugin with hyprpm is not possible as it gives an error in manifest issue.Would be great if this plugin had support for hyprpm

**Comment by ItsDrike** [comment]
Added in https://github.com/ItsDrike/hyprland-dwindle-autogroup/commit/9ec31792fe134b1503a67b0b5d2d96f247608f66
