### ISSUE TITLE
Hyprland compositor crashes when using togglegroup dispatcher on a single window 

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#2]
### Issue Summary
When using the toggle group dispatcher on a single window or trying to ungroup an already tiled child node using the toggle group feature, the hyprland compositor crashes.

### Steps to reproduce
1. use togglegroup in a single pane for example open kitty and just use the toggle group dispatcher
2. Hyprland promptly crashes with step 1

### Expected behavior
Not to crash but either to toggle a group with a single node or not group at all

### Environment

- Operating System: Arch Linux x86_64 
- Hyprland version:```Hyprland, built from branch main at commit 2b4d96e0efe4ce4a13b8cdef0d1ff5981f674542dirty (examples: pull correct wlr dirs in example plugin).```
- plugin version: latest git

### Additional details

coredump : [https://paste.rs/Zn5](https://paste.rs/Zn5)
hyprland crash log: [https://paste.rs/3B6](https://paste.rs/3B6)

**Comment by ItsDrike** [comment]
Thanks for the report! Should be fixed by a9eedb1d72fac66ace9d38e7fcae1e98c41aa680
