### ISSUE TITLE
welp the plugin is broken again

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#6]
In the latest 0.29.1 update in arch , I cant compile the plugin.

these are the error logs

```
g++ -shared -g -fPIC --no-gnu-unique -std=c++23 `pkg-config --cflags pixman-1 libdrm hyprland` -Iinclude -DWLR_USE_UNSTABLE src/main.cpp -o dwindle-autogroup.so
In file included from /usr/local/include/hyprland/src/defines.hpp:1,
                 from /usr/local/include/hyprland/src/Window.hpp:3,
                 from src/main.cpp:3:
/usr/local/include/hyprland/src/includes.hpp:149:10: fatal error: ext-workspace-unstable-v1-protocol.h: No such file or directory
  149 | #include "ext-workspace-unstable-v1-protocol.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:26: all] Error 1
```

**Comment by ItsDrike** [comment]
I can't reproduce this issue. How did you install hyprland, via AUR? I've compiled hyprland from commit [96d555e8](https://github.com/hyprwm/Hyprland/commit/96d555e8e794627bfc561e294e148ab8a9961fcc), which corresponds to the git tag of `v0.29.1`. Building the plugin works without issues for me there. Maybe try compiling from source, and see if there's a difference in comparison to AUR.

From the error there, it seems like an issue originating in the Hyprland header files in `/usr/local/include/hyprland`. There is an include of a header file which apparently wasn't found. I can't do anything about those hyprland header files from the project's perspective though. Those are put there during hyprland installation, and should work properly. This seems like you're missing an entire header file in there.

If manual Hyprland compilation fixes the issue, let me know, or if you feel like it, you can analyze the `PKGBUILD` and see if you can find the culprit. If the issue really does persist even after installing Hyprland manually, could you try doing a git bisect and finding the actual hyprland commit from which this issue appears? From there, I should be able to at least see what change in hyprland caused this, and hopefully find out why it doesn't work on your system.

(git bisect means checking out the last commit at which things worked, so for you, probably the previous stable version, compile from that, and see if it works, if it does, run `git bisect good`, then check out v0.29.1, and do `git bisect bad`, git will now automatically check out versions to find the exact commit at which things stopped working (binary search), you can just keep using these 2 commands depending on whether the plugin compilation worked or not. After a while, git will tell you which commit was the faulty one.)

**Comment by structnull** [comment]
switching to hyprland-git fixes this issue
thanks for the response

**Comment by ItsDrike** [comment]
Still it is pretty odd that you even encountered such an issue, I don't use the AUR version, so it is possible that it's something to do with how it's built, the include files are there purely for plugins afaik, so even if they're missing it shouldn't affect hyprland itself. This means that it's possible the AUR installation doesn't build them or something, maybe that's the reason. Hard to say.

Well either way, glad you were able to fix it, I'm still kinda curious why this happened though.

**Comment by ItsDrike** [comment]
Re-closing the issue as can't repro, rather than completed/resolved.
